# Generated by Django 6.0.3 on 2026-03-23 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.TextField()),
                ('feedback', models.TextField()),
                ('mensagem', models.OneToOneField(db_column='id_Mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='feedbackmensagem', to='chat.mensagem')),
            ],
        ),
    ]
