# Generated by Django 6.0.3 on 2026-03-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mensagem',
            field=models.OneToOneField(db_column='id_Mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='feedbackmensagem', to='chat.mensagem'),
        ),
    ]
