from . import settings


BASE_DIR = settings.BASE_DIR
SECRET_KEY = settings.SECRET_KEY
ALLOWED_HOSTS = settings.ALLOWED_HOSTS
INSTALLED_APPS = settings.INSTALLED_APPS
MIDDLEWARE = settings.MIDDLEWARE
CORS_ALLOWED_ORIGINS = settings.CORS_ALLOWED_ORIGINS
CORS_ALLOWED_ORIGIN_REGEXES = settings.CORS_ALLOWED_ORIGIN_REGEXES
CORS_EXPOSE_HEADERS = settings.CORS_EXPOSE_HEADERS
ROOT_URLCONF = settings.ROOT_URLCONF
TEMPLATES = settings.TEMPLATES
WSGI_APPLICATION = settings.WSGI_APPLICATION
AUTH_USER_MODEL = settings.AUTH_USER_MODEL
AUTHENTICATION_BACKENDS = settings.AUTHENTICATION_BACKENDS
AUTH_PASSWORD_VALIDATORS = settings.AUTH_PASSWORD_VALIDATORS
LANGUAGE_CODE = settings.LANGUAGE_CODE
TIME_ZONE = settings.TIME_ZONE
USE_I18N = settings.USE_I18N
USE_TZ = settings.USE_TZ
STATIC_URL = settings.STATIC_URL
MEDIA_ROOT = settings.MEDIA_ROOT
MEDIA_URL = settings.MEDIA_URL
FIREBASE_CREDENTIALS_PATH = settings.FIREBASE_CREDENTIALS_PATH
CELERY_BROKER_URL = settings.CELERY_BROKER_URL
CELERY_RESULT_BACKEND = settings.CELERY_RESULT_BACKEND
CELERY_ACCEPT_CONTENT = settings.CELERY_ACCEPT_CONTENT
CELERY_TASK_SERIALIZER = settings.CELERY_TASK_SERIALIZER
CELERY_RESULT_SERIALIZER = settings.CELERY_RESULT_SERIALIZER
CELERY_TIMEZONE = settings.CELERY_TIMEZONE


DEBUG = False

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "test_db.sqlite3",
    }
}

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.MD5PasswordHasher",
]

MIGRATION_MODULES = {
    "user": None,
    "chat": None,
    "rag": None,
    "base_conhecimento": None,
    "analytics": None,
}
