# Generated by Django 6.0.3 on 2026-03-11 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_Conhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('caminho', models.TextField()),
                ('status', models.TextField()),
                ('base', models.ForeignKey(db_column='id_Base', on_delete=django.db.models.deletion.CASCADE, related_name='base_pai', to='base_conhecimento.base_conhecimento')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_dono', to='user.user')),
            ],
        ),
    ]
