# Generated by Django 6.0.3 on 2026-03-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_conhecimento',
            name='versao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
