# Generated by Django 6.0.3 on 2026-03-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0003_base_conhecimento_versao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base_conhecimento',
            old_name='data_atualizacao',
            new_name='data_criacao',
        ),
    ]
