# Generated by Django 6.0.3 on 2026-03-30 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0005_alter_documento_caminho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='caminho',
            field=models.FileField(max_length=255, upload_to='./', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
