# Generated by Django 6.0.3 on 2026-04-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0006_alter_documento_caminho'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.TextField(choices=[('PORTARIA', 'Portaria'), ('RESOLUCAO', 'Resolucao'), ('ROD', 'Rod')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='base_conhecimento',
            name='status',
            field=models.TextField(choices=[('ATIVO', 'Ativo'), ('DESATIVADO', 'Desativado')]),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.TextField(choices=[('ENVIANDO', 'Enviando'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluido'), ('ERRO', 'Erro')]),
        ),
    ]
