# Generated by Django 6.0.3 on 2026-04-26 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0007_documento_tipo_alter_base_conhecimento_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='caminho',
            field=models.FileField(max_length=255, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
