# Generated by Django 6.0.3 on 2026-03-11 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('role', models.TextField()),
                ('pergunta_original', models.TextField(blank=True, null=True)),
                ('pergunta_processada', models.TextField(blank=True, null=True)),
                ('intencao', models.TextField(blank=True, null=True)),
                ('chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chat.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.TextField()),
                ('mensagem_feedback', models.TextField()),
                ('mensagem', models.OneToOneField(db_column='id_mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_referencia', to='chat.mensagem')),
            ],
        ),
    ]
