# Generated by Django 6.0.3 on 2026-03-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='chat',
            field=models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='mensagem',
            field=models.OneToOneField(db_column='id_mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_referencia', to='chat.mensagem'),
        ),
    ]
