# Generated by Django 6.0.3 on 2026-04-06 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='tipo',
            field=models.TextField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='chat',
            field=models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.chat'),
        ),
    ]
