# Generated by Django 6.0.3 on 2026-04-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
