# Generated by Django 6.0.3 on 2026-03-11 02:35

import django.contrib.postgres.search
import pgvector.django.vector
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        CreateExtension('vector'),
        migrations.CreateModel(
            name='ChunkDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(default=dict)),
                ('text_search_tsv', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('mensagens', models.ManyToManyField(blank=True, related_name='chunks_utilizados', to='chat.mensagem')),
            ],
        ),
    ]
