# Generated by Django 6.0.3 on 2026-03-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chunkdocumento',
            table='data_rag_chunkdocumento',
        ),
    ]
