# Generated by Django 6.0.3 on 2026-03-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_chunkdocumento_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkdocumento',
            name='metadata',
            field=models.JSONField(db_column='metadata_', default=dict),
        ),
    ]
