# Generated by Django 6.0.3 on 2026-03-30 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('rag', '0003_alter_chunkdocumento_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(blank=True, default='', max_length=512)),
                ('chunk', models.ForeignKey(db_column='id_chunk', on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_chunks', to='rag.chunkdocumento')),
                ('mensagem', models.ForeignKey(db_column='id_mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_chunks', to='chat.mensagem')),
            ],
            options={
                'db_table': 'data_rag_mensagemchunk',
                'unique_together': {('chunk', 'mensagem')},
            },
        ),
    ]
