# Generated by Django 6.0.3 on 2026-03-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_mensagemchunk_alter_chunkdocumento_mensagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunkdocumento',
            name='mensagens',
        ),
    ]
