# Generated by Django 6.0.3 on 2026-03-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('rag', '0005_remove_chunkdocumento_mensagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkdocumento',
            name='mensagens',
            field=models.ManyToManyField(blank=True, related_name='chunks_utilizados', through='rag.MensagemChunk', to='chat.mensagem'),
        ),
    ]
